sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
        - cd $TRAVIS_BUILD_DIR/frontend
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
        - docker build -t failender/luxel:$TRAVIS_BRANCH .
        - docker push failender/luxel
